/* Generated By:JavaCC: Do not edit this line. our_example_3Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface our_example_3Constants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"a\"",
    "\"b\"",
    "\"c\"",
    "\"d\"",
    "\"e\"",
    "\"f\"",
  };

}
