/* Generated By:JavaCC: Do not edit this line. ExpressionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionConstants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\"4\"",
    "\"-\"",
    "\"1\"",
    "\"9\"",
    "\"3\"",
    "\")\"",
    "\"/\"",
    "\"7\"",
    "\"*\"",
    "\"+\"",
    "\"2\"",
    "\"6\"",
  };

}
