PARSER_BEGIN(our_example_3)

/** Simple brace matcher. */
public class our_example_3 {

  /** Main entry point. */
  public static void main(String args[]) throws ParseException {
    our_example_3 parser = new our_example_3(System.in);
    parser.S();
  }

}

PARSER_END(our_example_3)

/** Root production. */
void S() :
{}
{
  "a" A()
}

void A() :
{}
{
  "b" B()
}

void B() :
{}
{
  "c" C()
}

void C() :
{}
{
  "d" D()
}

void D() :
{}
{
  "e" E()
}

void E() :
{}
{
  "f"
}
