PARSER_BEGIN(our_example_6)

/** Simple brace matcher. */
public class our_example_6 {

  /** Main entry point. */
  public static void main(String args[]) throws ParseException {
    our_example_6 parser = new our_example_6(System.in);
    parser.S();
  }
}

PARSER_END(our_example_6)

/** Root production. */
void S() :
{}
{
  "a" B() C() "d"
}

void B() :
{}
{
  A() "b"
}

void A() :
{}
{
  "b"
}

void C() :
{}
{
  "c"
}
